#### Load the libraries

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Load the dataset and create copy of dataframe

In [16]:
df = pd.read_csv("../Dataset/aqi_in_india.csv")
df_copy = df.copy()

#### Represent features

In [17]:
df_copy.columns

Index(['country', 'state', 'city', 'station', 'last_update', 'latitude',
       'longitude', 'pollutant_id', 'pollutant_min', 'pollutant_max',
       'pollutant_avg'],
      dtype='str')

#### Use to get concise summary of a Dataframe

In [18]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 3371 entries, 0 to 3370
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3371 non-null   str
 1   state          3371 non-null   str
 2   city           3371 non-null   str
 3   station        3371 non-null   str
 4   last_update    3371 non-null   str
 5   latitude       3371 non-null   float64
 6   longitude      3371 non-null   float64
 7   pollutant_id   3371 non-null   str
 8   pollutant_min  3152 non-null   float64
 9   pollutant_max  3152 non-null   float64
 10  pollutant_avg  3152 non-null   float64
dtypes: float64(5), str(6)
memory usage: 289.8 KB

#### Number of different category in a column

In [19]:
print(f"Countries: {df_copy['country'].unique().tolist()} Numbers: {df_copy['country'].nunique()}\nStations: {df_copy['station'].nunique()}\nCities: {df_copy['city'].nunique()}")

Countries: ['India'] Numbers: 1
Stations: 508
Cities: 270

#### Describe descriptive statistics (Summarize the centeral tendency)

In [20]:
df_copy.describe()

          latitude    longitude  pollutant_min  pollutant_max  pollutant_avg
count  3371.000000  3371.000000    3152.000000    3152.000000    3152.000000
mean     22.584005    78.549626      27.505076      80.876269      49.719860
std       5.593817     4.726663      41.710872     104.429854      67.688558
min       8.514909    70.909168       1.000000       1.000000       1.000000
25%      19.053536    75.638133       5.000000      15.000000      10.000000
50%      23.221714    77.319699      14.000000      42.000000      27.000000
75%      27.196370    80.320270      30.000000      99.000000      56.000000
max      31.620000    94.636574     500.000000     500.000000     486.000000

#### Total missing values

In [21]:
df_copy.isnull().sum()
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 657

#### Total number of records in the dataset

In [22]:
df_copy.shape[0]

3371

#### Drop the duplicate values & drop null values

In [23]:
df_copy.duplicated().sum()
df_copy.drop_duplicates(inplace=True)
df_copy.dropna(inplace=True)
df_copy.shape[0]
data = df_copy.copy()
data.shape[0]

3152

In [24]:
data["datetime"] = pd.to_datetime(data["last_update"])
data["day"] = data["datetime"].dt.day
data["month"] = data["datetime"].dt.month
data["year"] = data["datetime"].dt.year

data["hour"] = data["datetime"].dt.hour
data = data.drop(columns=["last_update", "station", "country", "datetime"])
# data = data.pop(columns=['last_update'])
data.head()

,state,city,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg,day,month,year,hour
0,Assam,Sivasagar,26.987634,94.636574,PM2.5,14.0,24.0,19.0,11,3,2025,16
1,Assam,Sivasagar,26.987634,94.636574,PM10,22.0,38.0,26.0,11,3,2025,16
2,Bihar,Araria,26.146529,87.454184,NO2,3.0,45.0,22.0,11,3,2025,16
3,Bihar,Araria,26.146529,87.454184,NH3,6.0,7.0,6.0,11,3,2025,16
4,Bihar,Araria,26.146529,87.454184,SO2,16.0,24.0,21.0,11,3,2025,16

#### Encode Categorical columns 

It is used to convert categorical text to numerical values. It assign a unique integers to each distinct category. Typically ranging from 0 to n-1.

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
encoder = LabelEncoder()

data["city"] = encoder.fit_transform(data["city"])
data["state"] = encoder.fit_transform(data["state"])
data["pollutant_id"] = encoder.fit_transform(data["pollutant_id"])

data.head()

,state,city,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg,day,month,year,hour
0,2,232,26.987634,94.636574,5,14.0,24.0,19.0,11,3,2025,16
1,2,232,26.987634,94.636574,4,22.0,38.0,26.0,11,3,2025,16
2,3,14,26.146529,87.454184,2,3.0,45.0,22.0,11,3,2025,16
3,3,14,26.146529,87.454184,1,6.0,7.0,6.0,11,3,2025,16
4,3,14,26.146529,87.454184,6,16.0,24.0,21.0,11,3,2025,16

#### Select Features

In [27]:
features = [
    'city',
    'state',
    'pollutant_id',
    'year',
    'month',
    'day',
    'hour',
]

traget = 'pollutant_avg'

X = data[features]
y = data[traget]

data.to_csv("../Dataset/processed_data.csv", index=False)